
TR_ITEM(TID_Exit,				u8"退出",			"Exit")
TR_ITEM(TID_Setting,			u8"设置",			"Setting")
TR_ITEM(TID_Trajectory,			u8"轨迹线",			"Trajectory")
TR_ITEM(TID_P,					u8"P档退出",		"P Gears")
TR_ITEM(TID_Chassis,			u8"透明底盘",		"Transparent Chassis")
TR_ITEM(TID_RadarFullView,		u8"雷达激活全景",	"RadarFullView")
TR_ITEM(TID_IndicatorFullView,	u8"转向灯激活全景", "IndicatorFullView")
TR_ITEM(TID_Language,			u8"切换语言",		"Language")
TR_ITEM(TID_Theme,				u8"切换主题",		"Theme")
TR_ITEM(TID_Now,				u8"立刻",			"Now")
TR_ITEM(TID_30S,				u8"30秒后",			"30s")
TR_ITEM(TID_Tip0,				u8"倒车循迹已开启，请松开刹车", "Reverse tracking is engaged, please release the brake")
TR_ITEM(TID_DIS,				u8"50米", "50m")

TR_ITEM(TID_Auto, u8"自动泊车", "Auto")
TR_ITEM(TID_Control, u8"遥控泊车", "Control")
TR_ITEM(TID_Select, u8"自选车位", "Select")
TR_ITEM(TID_HPA, u8"记忆泊车", "HPA")
TR_ITEM(TID_AutoTip, u8"提示：保持直线行驶，距车位侧边0.5~1.5范围内", u8"Tip: Keep driving in a straight line, 0.5~1.5 away from the side of the parking space")
TR_ITEM(TID_AutoTip_Step1, u8"车位搜索中，请低速前进", "Searching Slot, please slow down")
TR_ITEM(TID_AutoTip_Step2, u8"未搜索到车位，请继续等待", "Slots not found, please wait")
TR_ITEM(TID_AutoTip_Step3, u8"搜索到车位，请选择停放车位", "Slots found, please select a slot")
TR_ITEM(TID_AutoTip_Step4, u8"请保持刹车，点击开始按钮", "Please Keep the brake, click button to start")
TR_ITEM(TID_AutoTip_Step5, u8"请松开刹车和方向盘", "Please release the brake and wheel")
TR_ITEM(TID_AutoTip_Step6, u8"自动泊车中", "Parking")
TR_ITEM(TID_AutoTip_Step7, u8"请注意周围环境", "Please pay attention to the surroundings")
TR_ITEM(TID_AutoTip_Step8, u8"监测到障碍物，请移除后继续自动泊车", "Obstruction detected, please remove and continue automatic parking")
TR_ITEM(TID_AutoTip_Step9, u8"障碍物已移除", "Obstruction removed")
TR_ITEM(TID_AutoTip_ParkDone, u8"泊车已完成，请驾驶员重新接管车辆", "Parking completed, driver to take over vehicle again")
TR_ITEM(TID_Control_Title0, u8"条件检测中", "Condition detection")
TR_ITEM(TID_Control_Title1, u8"条件检测中.", "Condition detection.")
TR_ITEM(TID_Control_Title2, u8"条件检测中..", "Condition detection..")
TR_ITEM(TID_Control_Title3, u8"条件检测中...", "Condition detection...")
TR_ITEM(TID_Control_Txt0, u8"请挂至P档", "Keep on P gear")
TR_ITEM(TID_Control_Txt1, u8"请打开车联助手APP", "Open the Car Assistant APP")
TR_ITEM(TID_Control_Txt2, u8"请保持手机蓝牙连接", "Keep mobile phone bluetooth connected")
TR_ITEM(TID_Control_Txt3, u8"请关闭车门、后备箱、引擎盖", "Close the doors, trunk, and hood")
TR_ITEM(TID_Control_Txt4, u8"钥匙不在车内", "Keys are not in the car")
TR_ITEM(TID_Progress_Txt0, u8"遥控泊车进行中......", "Progressing......")
TR_ITEM(TID_Progress_Txt1, u8"遥控泊车暂停", "Pause")
TR_ITEM(TID_Progress_Txt2, u8"遥控泊车完成", "Done")
TR_ITEM(TID_Select_Title, u8"温馨提醒", "Warm Tips")
TR_ITEM(TID_Select_Tip, u8"      用户请确保选择的车位合法合适且安全，\n      泊车过程请时刻注意观察车辆周围环境\n\n               拖动全景中的车位完成定位，\n               通过车位角度按钮微调角度", 
	" Please ensure the legal right and safty parking lots,\n Please pay attention to the enmoment while parking\n\n                Drag panorama of parking location,\n          Fine-tuning angle through the angle button")
TR_ITEM(TID_Select_Txt0, u8"拖动全景中的车位完成定位，通过车位角度按钮微调角度", "Drag and location, roating with the small button")
TR_ITEM(TID_Select_Txt1, u8"开始泊入", "Start")

TR_ITEM(TID_HPA_Agree, u8"我已阅读并同意《记忆泊车使用协议》和《数据保护规定》", "I have read and agree the <HPA Protocol> and <Data Protection Sets>")
TR_ITEM(TID_HPA_Accept, u8"接受并继续",	"Accept")
TR_ITEM(TID_HPA_Skip, u8"跳过", "Start")
TR_ITEM(TID_HPA_ChooseRoute, u8"路线选择", "Route Selection")
TR_ITEM(TID_HPA_Tutorial, u8"教程", "Tutor")
TR_ITEM(TID_HPA_Tutorial_Title0, u8"欢迎使用记忆泊车", "Welcome to HPA")
TR_ITEM(TID_HPA_Tutorial_Title1, u8"路径学习", "Learning Path")
TR_ITEM(TID_HPA_Tutorial_Title2, u8"从车机端启动记忆泊车", "Start HPA from vehicle")
TR_ITEM(TID_HPA_Tutorial_Title3, u8"从手机端启动记忆泊车", "Start HPA from your phone")
TR_ITEM(TID_HPA_Tutorial_Title4, u8"记忆泊车教程视频", "HPA video tutorial")
TR_ITEM(TID_HPA_Tutorial_Start, u8"开始使用", "Start")
TR_ITEM(TID_HPA_Tutorial_Page0, u8"这是记忆泊车教程第1页，它没有上一页，但是它有下一页，它的下一页是第2页。它不知道它的下一页是否有下一页。", "This is page 1 of the memory parking tutorial, it doesn't have a previous page, but it does have a next page, and its next page is page 2. It doesn't know if its next page has a next page.")
TR_ITEM(TID_HPA_Tutorial_Page1, u8"这是记忆泊车教程第2页，它既有上一页，也有下一页，它的上一页是第1页，下页是第3页。它不知道它的上一页是否有上一页，也不知道它的下一页是否有下一页。", "This is page 2 of the Memory parking tutorial, it has a previous page and a next page, the previous page is page 1 and the next page is page 3. It doesn't know if its previous page has a previous page, and it doesn't know if its next page has a next page.")
TR_ITEM(TID_HPA_Tutorial_Page2, u8"这是记忆泊车教程第3页，它既有上一页，也有下一页，它的上一页是第2页，下页是第4页。它不知道它的上一页是否有上一页，也不知道它的下一页是否有下一页。", "This is page 3 of the memory parking tutorial, and it has a previous page and a next page, the previous page is page 2 and the next page is page 4. It doesn't know if its previous page has a previous page, and it doesn't know if its next page has a next page.")
TR_ITEM(TID_HPA_Tutorial_Page3, u8"这是记忆泊车教程第4页，它既有上一页，也有下一页，它的上一页是第3页，下页是第5页。它不知道它的上一页是否有上一页，也不知道它的下一页是否有下一页。", "This is page 4 of the Memory parking tutorial, and it has both a previous page and a next page, the previous page is page 3 and the next page is page 5. It doesn't know if its previous page has a previous page, and it doesn't know if its next page has a next page.")
TR_ITEM(TID_HPA_Tutorial_Page4, u8"这是记忆泊车教程第5页，它没有下一页，但是它有上一页，它的上一页是第4页。它不知道它的上一页是否有上一页。", "This is page 5 of the Memory parking tutorial, it doesn't have a next page, but it does have a previous page, and its previous page is page 4. It doesn't know if its previous page has a previous page.")
TR_ITEM(TID_HPA_Card_Edit, u8"编辑", "Edit")