
TR_ITEM(TID_Exit,				u8"退出",			"Exit")
TR_ITEM(TID_Setting,			u8"设置",			"Setting")
TR_ITEM(TID_Trajectory,			u8"轨迹线",			"Trajectory")
TR_ITEM(TID_P,					u8"P档退出",		"P Gears")
TR_ITEM(TID_Chassis,			u8"透明底盘",		"Transparent Chassis")
TR_ITEM(TID_RadarFullView,		u8"雷达激活全景",	"RadarFullView")
TR_ITEM(TID_IndicatorFullView,	u8"转向灯激活全景", "IndicatorFullView")
TR_ITEM(TID_Language,			u8"切换语言",		"Language")
TR_ITEM(TID_Theme,				u8"切换主题",		"Theme")
TR_ITEM(TID_Now,				u8"立刻",			"Now")
TR_ITEM(TID_30S,				u8"30秒后",		"30s")
TR_ITEM(TID_Tip0,				u8"倒车循迹已开启，请松开刹车", "Reverse tracking is engaged, please release the brake")

TR_ITEM(TID_Auto, u8"自动泊车", "Auto")
TR_ITEM(TID_Control, u8"遥控泊车", "Control")
TR_ITEM(TID_Select, u8"自选车位", "Select")
TR_ITEM(TID_HPA, u8"记忆泊车", "HPA")
TR_ITEM(TID_AutoTip, u8"提示：保持直线行驶，距车位侧边0.5~1.5范围内", u8"Tip: Keep driving in a straight line, 0.5~1.5 away from the side of the parking space")
TR_ITEM(TID_Control_Title0, u8"条件检测中", "Condition detection")
TR_ITEM(TID_Control_Title1, u8"条件检测中.", "Condition detection.")
TR_ITEM(TID_Control_Title2, u8"条件检测中..", "Condition detection..")
TR_ITEM(TID_Control_Title3, u8"条件检测中...", "Condition detection...")
TR_ITEM(TID_Control_Txt0, u8"请挂至P档", "Keep on P gear")
TR_ITEM(TID_Control_Txt1, u8"请打开车联助手APP", "Open the Car Assistant APP")
TR_ITEM(TID_Control_Txt2, u8"请保持手机蓝牙连接", "Keep mobile phone bluetooth connected")
TR_ITEM(TID_Control_Txt3, u8"请关闭车门、后备箱、引擎盖", "Close the doors, trunk, and hood")
TR_ITEM(TID_Control_Txt4, u8"钥匙不在车内", "Keys are not in the car")
TR_ITEM(TID_Progress_Txt0, u8"遥控泊车进行中......", "Progressing......")
TR_ITEM(TID_Progress_Txt1, u8"遥控泊车暂停", "Pause")
TR_ITEM(TID_Progress_Txt2, u8"遥控泊车完成", "Done")
TR_ITEM(TID_Select_Title, u8"温馨提醒", "Warm Tips")
TR_ITEM(TID_Select_Tip, u8"      用户请确保选择的车位合法合适且安全，\n      泊车过程请时刻注意观察车辆周围环境\n\n              拖动全景中的车位完成定位，\n               通过车位角度按钮微调角度", 
	" Please ensure the legal right and safty parking lots,\n Please pay attention to the enmoment while parking\n\n                Drag panorama of parking location,\n          Fine-tuning angle through the angle button")
TR_ITEM(TID_Select_Txt0, u8"拖动全景中的车位完成定位，通过车位角度按钮微调角度", "Drag and location, roating with the small button")
TR_ITEM(TID_Select_Txt1, u8"开始泊入", "Start")

TR_ITEM(TID_PAP_Agree, u8"我已阅读并同意《记忆泊车使用协议》和《数据保护规定》", "I have read and agree the <Protocol Of Usage> and <Data Protection Sets>")
TR_ITEM(TID_PAP_Accept, u8"接受并继续",	"Accept")
TR_ITEM(TID_PAP_Skip, u8"跳过", "Skip")
TR_ITEM(TID_PAP_ChooseRoute, u8"路线选择", "Route Selection")
TR_ITEM(TID_PAP_Tutorial, u8"教程", "Tutor")