
TR_ITEM(ONE,		"1",	"⑴",	"一",	"One")
TR_ITEM(TWO,		"2",	"⑵",	"二",	"Two")
TR_ITEM(THREE,		"3",	"⑶",	"三",	"Three")
TR_ITEM(FOUR,		"4",	"⑷",	"四",	"Four")
TR_ITEM(FIVE,		"5",	"⑸",	"五",	"Five")
TR_ITEM(SIX,		"6",	"⑹",	"六",	"Six")
TR_ITEM(SEVEN,		"7",	"⑺",	"七",	"Seven")
TR_ITEM(EIGHT,		"8",	"⑻",	"八",	"Eight")
TR_ITEM(NINE,		"9",	"⑼",	"九",	"Nine")
TR_ITEM(TEN,		"10",	"⑽",	"十",	"Ten")
TR_ITEM(ELEVEN,		"11",	"⑾",	"十一",	"Eleven")
TR_ITEM(TWELVE,		"12",	"⑿",	"十二",	"Twelve")
TR_ITEM(THIRTEEN,	"13",	"⒀",	"十三",	"Thirteen")
TR_ITEM(FOURTEEN,	"14",	"⒁",	"十四",	"Fourteen")
TR_ITEM(FIFTEEN,	"15",	"⒂",	"十五",	"Fifteen")
